// Categorized food database curated from Kaggle, OpenFoodFacts, and popular international datasets
export const indianFoods = [
  // ── BREAKFAST ──
  { name: 'Poha (1 plate)', category: 'Breakfast', emoji: '🟡', cal: 250, p: 5, c: 45, f: 5 },
  { name: 'Idli (2 pieces with Chutney)', category: 'Breakfast', emoji: '⚪', cal: 160, p: 5, c: 32, f: 1.5 },
  { name: 'Masala Dosa (1 piece)', category: 'Breakfast', emoji: '🌯', cal: 350, p: 8, c: 60, f: 9 },
  { name: 'Plain Dosa (1 piece)', category: 'Breakfast', emoji: '🥞', cal: 210, p: 5, c: 42, f: 3 },
  { name: 'Rava Idli (2 pieces)', category: 'Breakfast', emoji: '🟡', cal: 170, p: 5, c: 32, f: 2 },
  { name: 'Medu Vada (2 pieces)', category: 'Breakfast', emoji: '🍩', cal: 270, p: 6, c: 30, f: 14 },
  { name: 'Upma (1 bowl)', category: 'Breakfast', emoji: '🥣', cal: 200, p: 5, c: 38, f: 4 },
  { name: 'Aloo Paratha (1 piece with curd)', category: 'Breakfast', emoji: '🥞', cal: 320, p: 7, c: 48, f: 11 },
  { name: 'Paneer Paratha (1 piece)', category: 'Breakfast', emoji: '🫓', cal: 320, p: 12, c: 42, f: 12 },
  { name: 'Methi Thepla (2 pieces)', category: 'Breakfast', emoji: '🫓', cal: 230, p: 6, c: 36, f: 7 },
  { name: 'Dhokla (3 pieces)', category: 'Breakfast', emoji: '🟨', cal: 160, p: 6, c: 28, f: 3 },
  { name: 'Sabudana Khichdi (1 plate)', category: 'Breakfast', emoji: '🍲', cal: 310, p: 3, c: 65, f: 5 },
  { name: 'Bread Omelette (2 eggs + 2 slices)', category: 'Breakfast', emoji: '🍳', cal: 340, p: 18, c: 28, f: 16 },
  { name: 'Puri Bhaji (2 puris + potato bhaji)', category: 'Breakfast', emoji: '🥯', cal: 390, p: 8, c: 55, f: 15 },
  { name: 'Moong Dal Cheela (1 piece)', category: 'Breakfast', emoji: '🥞', cal: 140, p: 8, c: 20, f: 3 },
  { name: 'Suji Halwa (1 small bowl)', category: 'Breakfast', emoji: '🥣', cal: 280, p: 4, c: 50, f: 8 },
  { name: 'Sprouts Salad (1 bowl)', category: 'Breakfast', emoji: '🥗', cal: 120, p: 9, c: 18, f: 1 },
  { name: 'Uttapam (1 piece)', category: 'Breakfast', emoji: '🥞', cal: 240, p: 6, c: 44, f: 4 },
  { name: 'Rava Dosa (1 piece)', category: 'Breakfast', emoji: '🥞', cal: 250, p: 5, c: 46, f: 5 },
  { name: 'Misal Pav (1 plate)', category: 'Breakfast', emoji: '🍲', cal: 420, p: 12, c: 58, f: 16 },
  { name: 'Oatmeal (1 bowl with Milk)', category: 'Breakfast', emoji: '🥣', cal: 180, p: 7, c: 32, f: 3 },
  { name: 'Cornflakes (1 bowl with Milk)', category: 'Breakfast', emoji: '🥣', cal: 150, p: 5, c: 28, f: 2 },
  { name: 'Fried Eggs (2 eggs)', category: 'Breakfast', emoji: '🍳', cal: 180, p: 12, c: 1, f: 14 },
  { name: 'Boiled Eggs (2 eggs)', category: 'Breakfast', emoji: '🥚', cal: 155, p: 13, c: 1, f: 11 },

  // ── LUNCH ──
  { name: 'Roti / Chapati (1 piece)', category: 'Lunch', emoji: '🫓', cal: 104, p: 3, c: 22, f: 0.5 },
  { name: 'Tandoori Roti (1 piece)', category: 'Lunch', emoji: '🫓', cal: 115, p: 4, c: 24, f: 0.5 },
  { name: 'Butter Naan (1 piece)', category: 'Lunch', emoji: '🫓', cal: 310, p: 8, c: 45, f: 11 },
  { name: 'Garlic Naan (1 piece)', category: 'Lunch', emoji: '🫓', cal: 320, p: 8, c: 46, f: 12 },
  { name: 'Basmati White Rice (1 bowl)', category: 'Lunch', emoji: '🍚', cal: 240, p: 4, c: 53, f: 0 },
  { name: 'Brown Rice (1 bowl)', category: 'Lunch', emoji: '🌾', cal: 215, p: 5, c: 46, f: 1.6 },
  { name: 'Jeera Rice (1 bowl)', category: 'Lunch', emoji: '🍚', cal: 260, p: 4.5, c: 55, f: 2.5 },
  { name: 'Veg Pulav (1 bowl)', category: 'Lunch', emoji: '🍚', cal: 280, p: 6, c: 54, f: 4 },
  { name: 'Chicken Biryani (250g)', category: 'Lunch', emoji: '🍗', cal: 450, p: 28, c: 50, f: 15 },
  { name: 'Veg Biryani (250g)', category: 'Lunch', emoji: '🍛', cal: 360, p: 10, c: 58, f: 10 },
  { name: 'Dal Tadka (1 bowl)', category: 'Lunch', emoji: '🍲', cal: 180, p: 9, c: 24, f: 5 },
  { name: 'Dal Makhani (1 bowl)', category: 'Lunch', emoji: '🍲', cal: 290, p: 11, c: 30, f: 14 },
  { name: 'Paneer Butter Masala (1 bowl)', category: 'Lunch', emoji: '🥘', cal: 360, p: 14, c: 14, f: 28 },
  { name: 'Palak Paneer (1 bowl)', category: 'Lunch', emoji: '🥬', cal: 220, p: 14, c: 12, f: 13 },
  { name: 'Chicken Curry (200g)', category: 'Lunch', emoji: '🍗', cal: 320, p: 25, c: 10, f: 15 },
  { name: 'Butter Chicken (200g)', category: 'Lunch', emoji: '🍛', cal: 420, p: 28, c: 14, f: 28 },
  { name: 'Fish Curry (200g)', category: 'Lunch', emoji: '🐟', cal: 260, p: 24, c: 8, f: 12 },
  { name: 'Egg Curry (2 eggs)', category: 'Lunch', emoji: '🥚', cal: 250, p: 16, c: 6, f: 18 },
  { name: 'Rajma Masala (1 bowl)', category: 'Lunch', emoji: '🥫', cal: 190, p: 10, c: 32, f: 3 },
  { name: 'Chole Masala (1 bowl)', category: 'Lunch', emoji: '🍲', cal: 240, p: 9, c: 38, f: 6 },
  { name: 'Aloo Gobhi (1 bowl)', category: 'Lunch', emoji: '🥦', cal: 150, p: 3, c: 18, f: 7 },
  { name: 'Bhindi Masala (1 bowl)', category: 'Lunch', emoji: '🥒', cal: 130, p: 3, c: 14, f: 6 },
  { name: 'Baingan Bharta (1 bowl)', category: 'Lunch', emoji: '🍆', cal: 140, p: 3, c: 15, f: 7 },
  { name: 'Yellow Moong Dal (1 bowl)', category: 'Lunch', emoji: '🍲', cal: 150, p: 10, c: 22, f: 2 },
  { name: 'Margherita Pizza (1 slice)', category: 'Lunch', emoji: '🍕', cal: 250, p: 10, c: 30, f: 9 },
  { name: 'Veggie Pizza (1 slice)', category: 'Lunch', emoji: '🍕', cal: 230, p: 9, c: 28, f: 8 },
  { name: 'Pepperoni Pizza (1 slice)', category: 'Lunch', emoji: '🍕', cal: 290, p: 12, c: 31, f: 12 },
  { name: 'Veg Burger (1 piece)', category: 'Lunch', emoji: '🍔', cal: 320, p: 11, c: 45, f: 10 },
  { name: 'Chicken Burger (1 piece)', category: 'Lunch', emoji: '🍔', cal: 380, p: 18, c: 40, f: 14 },
  { name: 'Cheese Burger (1 piece)', category: 'Lunch', emoji: '🍔', cal: 410, p: 20, c: 38, f: 18 },
  { name: 'Veg Hakka Noodles (1 plate)', category: 'Lunch', emoji: '🍝', cal: 340, p: 8, c: 58, f: 8 },

  // ── SNACK ──
  { name: 'Samosa (1 piece)', category: 'Snack', emoji: '📐', cal: 150, p: 3, c: 20, f: 8 },
  { name: 'Onion Pakoda (4 pieces)', category: 'Snack', emoji: '🧅', cal: 180, p: 3.5, c: 22, f: 9 },
  { name: 'Aloo Tikki (2 pieces)', category: 'Snack', emoji: '🍘', cal: 220, p: 4, c: 32, f: 8 },
  { name: 'Pani Puri / Golgappa (6 pieces)', category: 'Snack', emoji: '🟢', cal: 150, p: 3, c: 24, f: 4 },
  { name: 'Bhel Puri (1 plate)', category: 'Snack', emoji: '🥗', cal: 180, p: 4, c: 32, f: 4 },
  { name: 'Sev Puri (1 plate)', category: 'Snack', emoji: '🍘', cal: 240, p: 5, c: 38, f: 8 },
  { name: 'Dahi Puri (6 pieces)', category: 'Snack', emoji: '⚪', cal: 280, p: 6, c: 42, f: 10 },
  { name: 'Pav Bhaji (2 pavs + bhaji)', category: 'Snack', emoji: '🍞', cal: 450, p: 10, c: 62, f: 18 },
  { name: 'Vada Pav (1 piece)', category: 'Snack', emoji: '🍔', cal: 290, p: 6, c: 44, f: 10 },
  { name: 'Kachori (1 piece)', category: 'Snack', emoji: '🍘', cal: 190, p: 4, c: 26, f: 9 },
  { name: 'Roasted Chana (30g)', category: 'Snack', emoji: '🥜', cal: 110, p: 6, c: 16, f: 2 },
  { name: 'Masala Peanuts (30g)', category: 'Snack', emoji: '🥜', cal: 170, p: 6, c: 8, f: 13 },
  { name: 'Paneer Pakora (3 pieces)', category: 'Snack', emoji: '🧀', cal: 220, p: 10, c: 12, f: 15 },
  { name: 'Makhana / Foxnuts (20g)', category: 'Snack', emoji: '🍿', cal: 70, p: 2, c: 14, f: 0.2 },
  { name: 'Masala Chai (with milk & sugar)', category: 'Snack', emoji: '☕', cal: 75, p: 2, c: 12, f: 2 },
  { name: 'Filter Coffee (with milk & sugar)', category: 'Snack', emoji: '☕', cal: 85, p: 2.2, c: 14, f: 2.2 },
  { name: 'Sweet Lassi (1 glass)', category: 'Snack', emoji: '🥛', cal: 210, p: 5, c: 32, f: 6 },
  { name: 'Buttermilk / Chaas (1 glass)', category: 'Snack', emoji: '🥛', cal: 45, p: 2, c: 4, f: 1.5 },
  { name: 'Coconut Water (300ml)', category: 'Snack', emoji: '🥥', cal: 60, p: 1, c: 14, f: 0 },
  { name: 'Banana (1 medium)', category: 'Snack', emoji: '🍌', cal: 89, p: 1, c: 23, f: 0 },
  { name: 'Apple (1 medium)', category: 'Snack', emoji: '🍎', cal: 95, p: 0.5, c: 25, f: 0.3 },
  { name: 'Orange Juice (1 glass/250ml)', category: 'Snack', emoji: '🍊', cal: 110, p: 2, c: 26, f: 0.2 },
  { name: 'Apple Juice (1 glass/250ml)', category: 'Snack', emoji: '🧃', cal: 115, p: 0.5, c: 28, f: 0.1 },
  { name: 'Mango Juice / Maaza (250ml)', category: 'Snack', emoji: '🥭', cal: 150, p: 0.5, c: 37, f: 0.2 },
  { name: 'Watermelon Juice (1 glass)', category: 'Snack', emoji: '🍉', cal: 90, p: 1.5, c: 21, f: 0.2 },
  { name: 'Pineapple Juice (1 glass)', category: 'Snack', emoji: '🍍', cal: 120, p: 1, c: 29, f: 0.2 },
  { name: 'Lemonade / Nimbu Pani (1 glass)', category: 'Snack', emoji: '🍋', cal: 75, p: 0.2, c: 19, f: 0.1 },
  { name: 'French Fries (Medium)', category: 'Snack', emoji: '🍟', cal: 320, p: 3.4, c: 41, f: 15 },
  { name: 'Potato Chips (1 packet/50g)', category: 'Snack', emoji: '🥔', cal: 260, p: 3, c: 27, f: 16 },

  // ── DINNER ──
  { name: 'Paneer Tikka (Dry - 150g)', category: 'Dinner', emoji: '🍢', cal: 260, p: 18, c: 8, f: 18 },
  { name: 'Moong Dal Khichdi (1 bowl)', category: 'Dinner', emoji: '🍲', cal: 220, p: 8, c: 38, f: 4 },
  { name: 'Chicken Tikka (Dry - 6 pieces)', category: 'Dinner', emoji: '🍢', cal: 270, p: 32, c: 6, f: 13 },
  { name: 'Kadai Paneer (1 bowl)', category: 'Dinner', emoji: '🥘', cal: 320, p: 15, c: 10, f: 24 },
  { name: 'Khichdi with Ghee (1 bowl)', category: 'Dinner', emoji: '🍲', cal: 270, p: 8, c: 40, f: 8 },
  { name: 'Schezwan Fried Rice (1 plate)', category: 'Dinner', emoji: '🍛', cal: 360, p: 7, c: 62, f: 10 },
  { name: 'Tomato Soup (1 bowl)', category: 'Dinner', emoji: '🥣', cal: 90, p: 2, c: 15, f: 2 },
  { name: 'Paneer Wrap / Kathi Roll (1 piece)', category: 'Dinner', emoji: '🌯', cal: 320, p: 12, c: 38, f: 12 },
  { name: 'Chicken Wrap / Kathi Roll (1 piece)', category: 'Dinner', emoji: '🌯', cal: 340, p: 22, c: 34, f: 12 },
  { name: 'Tandoori Chicken (2 pieces)', category: 'Dinner', emoji: '🍗', cal: 280, p: 34, c: 4, f: 14 },
  { name: 'Gulab Jamun (1 piece)', category: 'Dinner', emoji: '🟤', cal: 150, p: 2, c: 25, f: 5 },
  { name: 'Jalebi (2 pieces)', category: 'Dinner', emoji: '🌀', cal: 220, p: 2, c: 38, f: 7 },
  { name: 'Rasgulla (1 piece)', category: 'Dinner', emoji: '⚪', cal: 125, p: 2.5, c: 26, f: 1.5 },
  { name: 'Kheer (1 bowl)', category: 'Dinner', emoji: '🥣', cal: 230, p: 6, c: 35, f: 7 },
  { name: 'Moong Dal Halwa (1 bowl)', category: 'Dinner', emoji: '🥣', cal: 320, p: 6, c: 42, f: 14 },
  { name: 'Penne Arrabiata Pasta (1 plate)', category: 'Dinner', emoji: '🍝', cal: 380, p: 12, c: 60, f: 10 },
  { name: 'Mac & Cheese (1 bowl)', category: 'Dinner', emoji: '🧀', cal: 420, p: 15, c: 48, f: 18 }
];
